# Generated by Django 5.2

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_username_role_choices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="department",
        ),
    ]
