# Generated by Django 5.2.7 on 2026-05-15 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_history_board_settings'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_column__c4dd04_idx',
            old_name='tasks_task_col_ent_idx',
        ),
    ]
